### ISSUE TITLE
What license is the code released under?

### ISSUE THREAD

**Issue by GoodOlClint** [egiust/SousVideAdaptativeArduino#4]
The post on Instructables has a Creative Commons by-nc-sa license, but this code doesn't have a license attached. Since Creative Commons [recommends against using their licenses for software](https://wiki.creativecommons.org/FAQ#Can_I_use_a_Creative_Commons_license_for_software.3F), is there a separate license for the source-code on it's own?

**Comment by egiust** [comment]
Hi GoodOlClint .
The github code lives separate from the Instructables how to. As I did not chose a license under the github, I guess the following apply : 

*What happens if I don't choose a license?*

*You're under no obligation to choose a license. It's your right not to include one with your code or project, but please be aware of the implications. Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work.*

I'm not familiar with licensing problematics, so I guess I was happy with this when I first released the source code. So let's say you can use it and modify it, but if some day you make millions using it, please do remember that it's copyrighted. :)

If you can suggest a license which can accomodate that, I'd probably add it to the repo.

**Comment by GoodOlClint** [comment]
[Here is a good blog post](http://blog.codinghorror.com/pick-a-license-any-license/) about one person's trouble with not picking a license. My main concern is that *technically* without a license attached to the code I can't legally make any modifications to it at all. An explicitly defined license still allows you to retain control over the code, but defines what I as a consumer can do with it.

If you haven't seen it I'd definitely check out [choosealicense.com](http://choosealicense.com/) for help picking a license.

**Comment by egiust** [comment]
Done; The code is now licensed under the GNU Affero General Public License

**Comment by GoodOlClint** [comment]
Awesome, thanks!
